language: node_js
node_js:
  - "6"
before_script:
    - npm install istanbul
    - npm install coveralls
script:
    - ./node_modules/.bin/istanbul cover ./node_modules/.bin/mocha -- --timeout 30000
after_script:
    - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
    - rm -rf ./coverage
